apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocs-default-sc-setter
rules:
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - patch
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocs-default-sc-setter
  namespace: openshift-storage
subjects:
  - kind: ServiceAccount
    name: ocs-default-sc-setter
    namespace: openshift-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocs-default-sc-setter
