apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: vm-sample-acm-placement-placement
  namespace: openshift-gitops
spec:
  numberOfClusters: 1
  prioritizerPolicy:
    configurations:
      - scoreCoordinate:
          builtIn: ResourceAllocatableCPU
        weight: 2
      - scoreCoordinate:
          builtIn: ResourceAllocatableMemory
        weight: 2