apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/giofontana/gitops-catalog/openshift-image-registry/overlays/vsphere

patches:
  - patch: |-
      - op: add
        path: /spec/storageClassName
        value: "ocs-storagecluster-ceph-rbd"
    target:
      kind: PersistentVolumeClaim
      name: image-registry-storage