kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-cluster-admin-rb
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: admin
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: gfontana@redhat.com    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
