apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgBXA4kg9VneHW7Um7CMK2C2KOVkEYJmanpmV5HE9IstTu+4OQqpzE03/1Ag+mpuKni4tENKE1RDGgNdw2qE3CQ0g1MmJP4Fwq4WCReHss92wqYoDo1PBzipSEdtm3PXyUyywp9ACSI8aN/mE4jXgUrBUoQjGaZvcE+ngQUVKAhVA5ZraYXCzltKIfhB+h1wtHXtLeAMTrrphfNoRfUxqVnA35G0tGBBR0pFkof3brlN1oUugnOyhIbEXALTcOJ179q+D7ZOXILl3CH2SZSnio3EDwQZ7enIX8asBQB6nKyjCzoFuSyKiu1VlRN/vpz1xnNl1JgxQrcAjMrPByylCO9q5UC/FYIWFo0aOTzxlMkfmQ42L20/UW5hmxrG5ifGS4TYyinZq0pdwXQ1cIDDGChZ8aC8/oKtlPOuX18dyOMJlPSdZZgZs9+AOgz3HWxZg1FKjLHmADFRaE1vYx34562v54vvVD70zDSdFRJ4r/OTUCnIsTCgzrIDjU3tALutG4avgTgm9LpfVcqqGwSCEMPjRaPAkNVIG52nVBC2qIKeCU8z1zAivdrL/V0SjeYFv1kpB8NGH/S66MWY7s4OqkoVNc5T0VodOJtuVYV8RJiNCxaXbp3AOzOYsfqvqQ8GAGKZEaI1JVYdTSkEniAj82GD6E1Dz5JKQ4bY2dmn+Y7PCorz9zs/Fe+quqtGgKVE4QZJrIStL4g/OMhII2j8n+qu4tS4mVDbG9U68WBAMoHBwIVbbv1T62Lj0eQwqItlR8S/6cUGO0CjUDsNXOizrMWRPSbs
  template:
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config

