apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - machine-mgmt.yaml
  - metallb.yaml
  - network.yaml
  - local-storage.yaml
  - openshift-data-foundation.yaml
  - openshift-image-registry.yaml
  - openshift-monitoring-persistence.yaml
  - openshift-virtualization.yaml
  - advanced-cluster-management.yaml
