apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - htpass-sealedsecret.yaml
  - google-secret-sealed.yaml
  - oauth-cluster.yaml
  - cluster-role-binding.yaml
  - consolenotification.yaml
  - remove-kubeadmin-job.yaml
