---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "5"
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../../../../operators/nvidia-gpu-operator/overlays/stable
  - github.com/giofontana/gitops-catalog/nvidia-gpu-operator/instance/overlays/time-sliced-10