kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: anythingllm-pvc
  namespace: anythingllm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  storageClassName: ocs-storagecluster-cephfs      
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: anythingllm-env-pvc
  namespace: anythingllm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: ocs-storagecluster-cephfs      