apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: anythingllm
  namespace: anythingllm
spec:
  host: chatgft.gfontana.me
  to:
    kind: Service
    name: anythingllm-service
  port:
    targetPort: notebook-port
  tls:
    termination: edge