apiVersion: v1
kind: Service
metadata:
  name: anythingllm-service
  namespace: anythingllm
spec:
  selector:
    app: anythingllm
  ports:
    - name: notebook-port
      port: 3001
      targetPort: 3001