---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../../../../operators/advanced-cluster-management/overlays/release-2.15
  - ../../../configuration/advanced-cluster-management
  - github.com/giofontana/gitops-catalog/advanced-cluster-management/instance/observability/
