kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    openshift.io/display-name: sdxl-storage
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: nfs.csi.k8s.io
    volume.kubernetes.io/storage-provisioner: nfs.csi.k8s.io
  resourceVersion: '98858047'
  name: sdxl-storage
  uid: 25d8da2d-79f7-49a9-a76f-b808c0980bd8
  creationTimestamp: '2026-01-14T22:05:09Z'
  namespace: llm-models
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pvc-25d8da2d-79f7-49a9-a76f-b808c0980bd8
  storageClassName: nfs-ssd-csi
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
