apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/giofontana/gitops-catalog/nvidia-gpu-operator/instance/overlays/time-sliced-10

patches:
  - path: patch-gpu-cluster-policy.yaml
    target:
      kind: ClusterPolicy
      name: gpu-cluster-policy
