apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgCr31yqmBlWbkufapFiAN+AL/sozqKBogcNCbsseiF925qkUtdMoiAKWbOO1q8LIaftro8nXrx+JAmNIarL2/L+v5PujYfQeHDPUahod2H0GrMZuR+o9vOezgdwGjiS9Ml2kHcshdNGpDRTnZG0Z77sZ5Frs+c4QgdoV9ay+XEcWAOKG96ww0KyFPdtBoyhEeJr10RkUEdqW0+oHvKY7N5qrWDxKWMcl7oSPY8KVL0EE3prsV+iDDA0CfWCTBwfunYrQhuiZs3rvK4vsu2HFLnRFyGHYVPQAsXMAphN/UOrn2Xw1I2Pho6dS5XMeYDa2vwdhDt7TKSs4Zhcibo+ZeP0IcpVUO7oiEtJ7CoEys6vggsnWrFidv+MJt18yn2kXt6v9msVBndYIVAbsDLBpe3HmGLB7PWdsloKBQSLm9Jfwy4ve4OBDjRU5pIRA0ALKrcgf0i/lM9INyWBP8dLz4Lsob6OdWZH6I4lJ2VGWyUATw/h4zmrn52RL/M3sYO0FNX06pf8EzEsiAJiVazHCQndvKH0kk+c5bG/BD+9vr0K3gw2mY3AEOVqh5ho0BhoOnYZ/NW1l6qENhyNrAZxQuwqcXB19/aY1WAS2jwIyCKSZ0QwXWTwG+PAjzmgFCL8xjsmD+RXLVCG6Tcy/bWxkAvhjya3zW8FE0hWPaywOPgdPn3Yj98ZY7s+FOwCILmALUcqGUnQThb1PdLBDRo1JP3HBrEXy+xXKf+zfZuU3pXEnYakTA==
  template:
    metadata:
      creationTimestamp: null
      name: google-secret
      namespace: openshift-config
    type: Opaque

