apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hdd-disks-workaround-master.yaml
  - hdd-disks-workaround-worker.yaml
  - storagecluster.yaml
  - ocsinitialization.yaml
