apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan102
  namespace: default
spec:
  config: '{
    "name":"vlan102",
    "type":"ovn-k8s-cni-overlay",
    "cniVersion":"0.4.0",
    "physicalNetworkName":"trunk",
    "vlanId": 102,
    "topology":"localnet",
    "netAttachDefName":"default/vlan102"
    }'