apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bart-bmc-secret
  namespace: openshift-machine-api
spec:
  encryptedData:
    password: AgBC1mQ7kP43MVgWft1KMLB3B0PQn5oeJoozkWzy7bWFo+pN+gK/Rm6cCjBCkYI0lKrJh75uujiD/Lf2Ik9aaWp21ypJHvHLcNYUqKYUmbFGOAE0p8XqDOWG7UTY09iQtx3bYVzbxT6sAFJYkcktV6YEpptTvbeIBjvIt6HhPLCTmly2FD2tc4vV3EpcR8DTcmFEsYK8o4j4QilCrgsInjF4ZZl4I0hExDT/GYKnqV5KZQiymCLek+z+KQc9rGJF5TEYfJxq02Qh0SKyNvwARZmKhf1StGbPZgtQ2MS36Du0P8xk7Cxuh1fGh7OXpe4DjenJSftuDCc2hK8MGXdShPELuzWevOHR19TC99utqodPsr4lrGa/jGCgZVzSJt60Fpyi5ZTL+K/GcadQKjUlEHcfnCdTUmoAKm4Gl82z6WK/BS23w/d6JU8CYHUz+E7Wrakq9BX/7qPEQ2HASrIeKF+XXOQ1Olv405aF9L7hy4pIp5PdrbD0mR83bvBXO4AJQNEJM7K6TyiZV5xnOthoaLondTbr5d3MHnrgrtqa3fBQGwC8elMIr3gXslDRTVqdUQpTKTZtKP8onrPaTKOqfw+DIPvpAp2rDpIut8b50/tQHQNjaVyiIG7QdTVlbGT5hXd/4fy5SjUQz3V9acfMz1a8Ikn5MWLiSfExUBPdB5p2aaZM0zqLIVloCQVpSXhTTurCM44aIWAY5Q==
    username: AgA6LLYBrHTSGG5Ew2CYgmBeO77DavrF0hQThGDqJdGbT6Zx/yfZf3Fl936SHhsJ1OCoyKqj+RbP2PPy25tO1lcZbKd9lToiER9myqYa3gvQNQdTVombjS2s+OwUZeKoZV9bDAm7JV4rv+PsTM8T3nnd9o/pfUta0lRFvZI+afro7K8QPDVZOEOArsW0fIUnA4ZWfTCYpP1Jngo+uAclC7sHXuAUPP/DiyKn0zUuHeW9LFyz9K4jMLBEerF0nLm64wkfbCSYomoqg7/QGYBUY3keQ581dYpsmjaxYhJ4cOGh6ES/4A+Y1wI89l2wc0YTri36Itfvq5mdhz3Yf1xYoqx5uCKej8PDWAAp+F+9PSk44hdqMy0iVmSvx08m/dSznWXSBHiQXAOd00OrI65JMhMpoYIJei1DfU6FpmLl5nbime0YYq6x+zlHW2xkOlvCbXzK9j7Pq2Km+Bhd1YJYw5YwYoaA16GrxyBADB8p8GtBAXAkl1/VEslsJLR/yVYV9fz/9gmQS3rVzIAxxzWpMKkePU2DarcpgxAxnXjXm3XPR38lB2HVGsiaERFIj0+s3dJh4c8f5pScngV4N3nhRX9ylKpwxrhb4O+o/O6yxXRsjAe3v7qmM1pTdTMHD35A8YAO10/6gKtFQDcMGyRVheu7XAjvJ3qagIrtzHskLNsmyT6h/4bDMGBlvYT2rJPG+hcMeHNG
  template:
    metadata:
      creationTimestamp: null
      name: bart-bmc-secret
      namespace: openshift-machine-api
    type: Opaque

