apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: master-kubeletconfig
spec:
  autoSizingReserved: true 
  kubeletConfig:
    maxPods: 500  
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/master: "" 