apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machineset-replicas-setter
rules:
  - apiGroups: ["machine.openshift.io"]
    resources:
      - machinesets
    verbs:
      - get
      - list
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: machineset-replicas-setter
  namespace: openshift-machine-api
subjects:
  - kind: ServiceAccount
    name: machineset-replicas-setter
    namespace: openshift-machine-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: machineset-replicas-setter
