apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: worker-kubeletconfig
spec:
  autoSizingReserved: true 
  kubeletConfig:
    maxPods: 500
    podsPerCore: 0
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/worker: "" 