apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management
spec:
  channel: release-2.15
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: advanced-cluster-management.v2.15.0
---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  availabilityConfig: High
  localClusterName: local-cluster
  overrides:
    components:
      - configOverrides: {}
        enabled: true
        name: app-lifecycle
      - configOverrides: {}
        enabled: true
        name: cluster-lifecycle
      - configOverrides: {}
        enabled: true
        name: cluster-permission
      - configOverrides: {}
        enabled: true
        name: console
      - configOverrides: {}
        enabled: true
        name: grc
      - configOverrides: {}
        enabled: true
        name: insights
      - configOverrides: {}
        enabled: true
        name: multicluster-engine
      - configOverrides: {}
        enabled: true
        name: multicluster-observability
      - configOverrides: {}
        enabled: true
        name: search
      - configOverrides: {}
        enabled: true
        name: submariner-addon
      - configOverrides: {}
        enabled: true
        name: volsync
      - configOverrides: {}
        enabled: false
        name: cluster-backup
      - configOverrides: {}
        enabled: false
        name: edge-manager-preview
      - configOverrides: {}
        enabled: false
        name: fine-grained-rbac-preview
      - configOverrides: {}
        enabled: false
        name: siteconfig
      - configOverrides: {}
        enabled: false
        name: cnv-mtv-integrations-preview
  separateCertificateManagement: false