apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment-cpu.yaml
  - frigate-config-secret-sealed.yaml
  - frigate-db-pvc.yaml
  - frigate-media-pvc.yaml
  - rolebinding.yaml
  - route.yaml
  - service.yaml
  - sa.yaml