apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config-secret-sealed.yaml
  - db-pvc.yaml
  - media-pv.yaml
  - media-pvc.yaml
  - rolebinding.yaml
  - route.yaml
  - service.yaml
  - sa.yaml