kind: PersistentVolume
apiVersion: v1
metadata:
  name: media-pv
spec:
  claimRef:
    namespace: frigate
    name: media-pvc
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/mnt/pool0/media/cameras"
    server: "192.168.1.3"
