apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frigate-web
  namespace: frigate
spec:
  host: frigate.gfontana.me
  to:
    kind: Service
    name: frigate-service
    weight: 100
  port:
    targetPort: https-ui
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None